name: CI

on:
  push:
    branches: [develop, main, 'feature/*', 'release/*', 'hotfix/*']
  pull_request:
    branches: [develop, main]

env:
  NODE_ENV: test
  FORCE_COLOR: 2

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm lint

  test:
    name: Test & Coverage
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run tests
        run: pnpm test
      - name: Run coverage
        run: pnpm test:coverage
      - name: Enforce coverage threshold
        run: |
          COVERAGE=$(grep -Po 'All files[^|]*\|\s*\K[\d.]+' coverage/lcov-report/index.html | head -1)
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "::error::Test coverage ($COVERAGE%) is below 90%" && exit 1
          fi
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write
