name: Release

on:
  push:
    branches:
      - main
      - 'release/*'

jobs:
  release:
    name: Release & Tag
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Generate changelog
        run: pnpm changelog || echo 'No changelog script defined.'
      - name: Bump version and tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git tag v$VERSION
          git push origin v$VERSION
    permissions:
      contents: write
      actions: read
